### ISSUE TITLE
Proposed challenge: Junctions in Korea

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-ideas#1]
_From @mxa on August 13, 2015 5:4_

Junctions and their names are very important in Korea and Japan, because people will reference those (instead of the street names) to describe a route or location. A junction with a name will be rendered in Mapnik, but unfortunately many junctions are mapped (imported?) as single points close to the actual junction. Like this one: https://www.openstreetmap.org/node/414694520
Task would be to move those points into the actual junction and fix the naming scheme.

_Copied from original issue: osmlab/maproulette#345_

**Comment by mvexel** [comment]
How could you select these from the data? Is there a common tag?

**Comment by mvexel** [comment]
[This](http://overpass-turbo.eu/s/b09) query yields 3026 such junctions:

![screenshot 2015-08-17 16 02 41](https://cloud.githubusercontent.com/assets/120452/9317514/6a26d63c-44f9-11e5-8151-17956c736e60.png)

Saving the data in [a gist](https://gist.github.com/mvexel/454735d9ca96c0237222) for later.

**Comment by mvexel** [comment]
_From @mxa on August 18, 2015 2:53_

That there is this horizontal border makes me think that someone has messed up some automated import process. Why is the example point I linked to, not showing up in the overpass-turbo query?

**Comment by mvexel** [comment]
your example does not have a `junction=yes` tag.

**Comment by mvexel** [comment]
_From @mxa on August 18, 2015 8:26_

Since not all of these points have a junction=yes tag, maybe one could search for loose points with words in the values that end either *ogeori, *오거리, *negeori, *네거리, *sageori, *사거리, *samgeori, *삼거리, *kyocharo, *교차로

This is what they mean (Quoting Wesley Woo-Duk Hwang-Chung):

> Ogeori (오거리)= 5-way intersection
> Negeori (네거리) = Sageori (사거리) = 교차로 = 4-way intersection = crossroads
> Samgeori (삼거리) = 3-way intersection = T-junction
> 
> I've often seen these labeled as "junction" on road signs, though, lost-in-translation notwithstanding. I suppose "n-way junction" might work.

**Comment by mvexel** [comment]
_From @mxa on October 21, 2015 14:48_

Here is a page in the wiki which lists the intersections and how they should be translated to English.
https://wiki.openstreetmap.org/wiki/Korea_Naming_Convention#Common_Hangeul_expressions

**Comment by mvexel** [comment]
_From @mxa on July 1, 2016 4:59_

Anything you need to make this happen?

**Comment by mxa** [comment]
Added: http://maproulette.org/map/1460/
