### ISSUE TITLE
Proposed challenge: Korean bridges as nodes

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-ideas#2]
_From @mxa on August 13, 2015 3:55_

In South Korea there are a lot of features which have obviously been imported. Like bridges, which are mapped as points instead of as a segment of a way (road, train track, etc).Here is an example: http://www.openstreetmap.org/node/414964945#map=19/35.47293/128.25836  Additionally the naming convention has changed, so that instead of `bridge:name=봉수교 (Bongsugyo)` it should be `name=봉수교`, `name:kr=봉수교`, `name:en=Bongsu Bridge`, `name:ko_rm=Bongsugyo`
A few meters north-west of the example point are two more nodes along the highway that mark beginning and end of a bridge.

Here is more about mapping bridges in Korea: http://wiki.openstreetmap.org/wiki/Korea_bridges

_Copied from original issue: osmlab/maproulette#344_

**Comment by mvexel** [comment]
Would this pertain to all nodes that are tagged bridge=yes? Or is there a different / better way to query these nodes?

**Comment by mvexel** [comment]
If it is that simple, this should be the source dataset: http://overpass-turbo.eu/s/aZU

**Comment by mvexel** [comment]
(Assuming you mean South Korea when you speak about Korea.)

**Comment by mvexel** [comment]
_From @mxa on August 17, 2015 21:19_

Yes,  AFAIK there was no such import in North Korea, but I didn't check.

**Comment by mvexel** [comment]
Saving the data in a [gist](https://gist.github.com/mvexel/bf808ed5a17098e29b98) for later.

**Comment by mvexel** [comment]
_From @mxa on July 2, 2016 2:27_

This one is a hot candidate too. Please move :)

**Comment by mxa** [comment]
Thanks

**Comment by mxa** [comment]
I tried to make this into a challenge but it doesn't seem to work. http://maproulette.org/map/403

**Comment by mxa** [comment]
Here is the challenge: http://maproulette.org/map/403
