### ISSUE TITLE
Missing addresses shops

### ISSUE THREAD

**Issue by sjib** [maproulette/challenge-ideas#5]
I would like to create a task that helps me add missing addresses. I am trying to set a challenge with the following overpass query. This one works in overpass - but in maproulette the challenge fails to build.

Is the overpass query correct for maproulette?

> /*
This is an example Overpass query.
Try it out by pressing the Run button above!
You can find more examples with the Load tool.
*/
[out:json][timeout:250];
// gather results
(
  // query part for: shop=supermarket and address!=* and key!~/addr:.[]
  area[name = "Bern"]->.a;
(  node (area.a) ["shop"="supermarket"][!"address"][!"addr:city"][!"addr:street"][!"addr:housenumber"][!"addr:postcode"]);

);
// print results
out body geom qt;
>;

Any other hints?

**Comment by mvexel** [comment]
sorry for only replying now..
Here's the query that worked for me:

```
[out:json][timeout:250];
(
  area[name = "Bern"]->.a;
(  node (area.a) ["shop"="supermarket"][!"address"][!"addr:city"][!"addr:street"][!"addr:housenumber"][!"addr:postcode"]);
);
out body geom qt;
```

[Challenge](http://maproulette.org/mr3/challenge/2987/task/4652471) (test, not discoverable through search)

**Comment by sjib** [comment]
Thanks
