### ISSUE TITLE
All highways=* going over a waterway=river without a bridge=*

### ISSUE THREAD

**Issue by Spanholz** [maproulette/challenge-ideas#6]
I thought of a new challenge that would show all the not mapped bridges over rivers in OpenStreetMap. This would be quite similar to the mapping of the missing level_crossing challange not long ago.

If somebody, maybe @mmd-osm himself, could lead me in the right direction how to do such a Overpass query, I would be very happy to add this challenge myself to the Maproulette.

Regiom: US, but could also be used worldwide

Thanks Spanholz

**Comment by mmd-osm** [comment]
keep right! already supports this kind of analysis via 'overlapping ways --> highway-waterway' + 'highway-riverbank'. I guess there's probably limited benefit reimplementing this stuff as Overpass query.

https://keepright.at/report_map.php?zoom=11&lat=33.91162&lon=-117.89709&layers=B0T&ch=0%2C202&show_ign=1&show_tmpign=1

**Comment by Spanholz** [comment]
Thanks for the quick reply. I thought there would be more errors of this kind. Didn't even thought of Keep Right.
